# Generated by Django 6.0 on 2026-01-05 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='donor_email',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='donor_name',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='donor_phone',
        ),
    ]
