# Generated by Django 6.0 on 2026-01-11 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_meal_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodSafety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('inspection_date', models.DateField()),
                ('inspector_name', models.CharField(blank=True, max_length=100)),
                ('temperature_celsius', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('checklist', models.TextField(blank=True, help_text='Checklist or JSON lines')),
                ('status', models.CharField(choices=[('ok', 'OK'), ('warning', 'Warning'), ('critical', 'Critical')], default='ok', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-inspection_date', '-created_at'],
            },
        ),
    ]
