# Generated by Django 6.0 on 2026-01-11 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_foodsafety'),
        ('registration', '0004_caregiver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reassessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_date', models.DateField()),
                ('assessor_name', models.CharField(blank=True, max_length=100)),
                ('score', models.PositiveSmallIntegerField(blank=True, help_text='Numeric score representing need level', null=True)),
                ('notes', models.TextField(blank=True)),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reassessments', to='registration.member')),
            ],
            options={
                'ordering': ['-assessment_date', '-created_at'],
            },
        ),
    ]
