# Generated by Django 6.0 on 2026-01-11 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_reassessment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoodSafety',
        ),
        migrations.DeleteModel(
            name='Reassessment',
        ),
    ]
