# Generated by Django 6.0 on 2026-01-11 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_ingredient_receipt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={},
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='expiration_date',
            new_name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='unit',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='status',
            field=models.CharField(choices=[('good', 'Good'), ('warning', 'Warning'), ('critical', 'Critical')], default='good', max_length=10),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Receipt',
        ),
    ]
