# Generated by Django 6.0 on 2026-01-05 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=150)),
                ('contact_person', models.CharField(max_length=100)),
                ('org_email', models.EmailField(max_length=254, unique=True)),
                ('org_phone', models.CharField(max_length=20)),
                ('org_address', models.TextField()),
                ('org_postal', models.CharField(max_length=10)),
                ('services', models.JSONField()),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
